[metadata]
name = rasor
version = 0.3.0
author = Benjamin Jung
description = A Python package for selecting isotopic ratios for nuclear archaeology
license = BSD-3-Clause

[options]
packages = find:
python_requires = >=3.10
install_requires = 
    numpy
    tqdm>=4.65.0
    scipy>=1.11
    radioactivedecay>=0.4.22
    pandas>=2
    mpi4py>=3.1
    psutils
    gaussianprocesses@git+ssh://github.com/jung-benjamin/gp-surfer.git

    

[options.entry_points]
console_scripts =
    run_ratio_selection = rasor.command_line:run_ratio_selection
    run_pre_selection = rasor.command_line:run_pre_selection
    run_post_processing = rasor.command_line:run_post_processing
    plot_genetic_evolution = rasor.command_line:plot_genetic_evolution
    run_aftermath = rasor.command_line:run_aftermath

[options.packages.find]
include = 
    rasor
    rasor.*
